/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptography;
import java.io.UnsupportedEncodingException;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Acer
 */
public class E7 extends javax.swing.JFrame {

    /**
     * Creates new form E7
     */
    public E7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ec = new javax.swing.JTextArea();
        re = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ke = new javax.swing.JTextField();
        JButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        se = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pa = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ec.setBackground(new java.awt.Color(0, 0, 0));
        ec.setColumns(20);
        ec.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ec.setForeground(new java.awt.Color(255, 255, 255));
        ec.setRows(5);
        jScrollPane1.setViewportView(ec);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, 140));

        re.setBackground(new java.awt.Color(0, 0, 0));
        re.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        re.setForeground(new java.awt.Color(255, 255, 255));
        re.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        getContentPane().add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 310, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receiver address");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 40));

        ke.setBackground(new java.awt.Color(0, 0, 0));
        ke.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ke.setForeground(new java.awt.Color(255, 255, 255));
        ke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        getContentPane().add(ke, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 310, 40));

        JButton1.setBackground(new java.awt.Color(0, 0, 0));
        JButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JButton1.setForeground(new java.awt.Color(255, 255, 255));
        JButton1.setText("Send");
        JButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(JButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 190, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sender address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        se.setBackground(new java.awt.Color(0, 0, 0));
        se.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        se.setForeground(new java.awt.Color(255, 255, 255));
        se.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        getContentPane().add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Encrypted message");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Receive");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 190, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sender's Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        pa.setBackground(new java.awt.Color(0, 0, 0));
        pa.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        pa.setForeground(new java.awt.Color(255, 255, 255));
        pa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        getContentPane().add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter key");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cryptography/bk.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
       //final String username = se.getText();
        //final String password = pa.getText();
        //final String rec = re.getText();
        final String username = "chakravyuh111@gmail.com";
        final String password = "nikhilhello123";
        final String rec = "chakravyuh222@gmail.com";
        final String enc=ec.getText();
        final String key=ke.getText();
        
        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587"); // 465

        Session session = Session.getInstance(props,
          new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                
                return new PasswordAuthentication(username, password);
            }
          });

        try {

//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dbname","dbuser","dbpass");
//
//            Statement st = con.createStatement();
//            PreparedStatement pst = con.prepareStatement("SQL query");
//            
//            boolean b = st.execute("SQL query"); // DDL, DML, TCL
//            int status = st.executeUpdate("SQL query");
//            ResultSet rst = st.executeQuery(); // only for SELECT queries
            
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse(rec));
            //message.setRecipients(Message.RecipientType.CC,
            //InternetAddress.parse(rec));
            
            message.setSubject("Cryptography solutions Pvt Ltd");
            //https://www.google.com/settings/security/lesssecureapps
            
            message.setText("Encrypted Message:"+enc+"\nKey:"+key);

            Transport.send(message);
            javax.swing.JOptionPane.showMessageDialog(null, "Email Sent ");
            System.out.println("Done");
            

        } catch (MessagingException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.toString());
            throw new RuntimeException(e);            
        }
    }//GEN-LAST:event_JButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String abc = E4.finalvalue;
        String def = E4.finalkey;
        System.out.println(def);  
        ec.setText(abc);
        ke.setText(def);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton1;
    private javax.swing.JTextArea ec;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ke;
    private javax.swing.JPasswordField pa;
    private javax.swing.JTextField re;
    private javax.swing.JTextField se;
    // End of variables declaration//GEN-END:variables
}
